on:
  issues:
    types: [opened]
name: IssueOps - Demo
jobs:
  act-on-issue:
    runs-on: ubuntu-latest
    if:  startsWith(github.event.issue.title, 'demo') || startsWith(github.event.issue.title, 'reset')
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Reset demo if a demo or reset issue was opened
        run: ./scripts/reset-demo.sh "${{ github.event.issue.body }}" "${{ github.event.issue.number }}"
        env:
          GITHUB_COM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
